---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: default-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default-local-storage
  resources:
    requests:
      storage: 100Mi
