---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: generic-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default-local-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker0
          - worker2

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: generic-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#  - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: default-local-storage
#  local:
#    path: /mnt/data
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - worker0
