# actual mount dirs as noted in # kind: PersistentVolume.spec.hostpath.path
# need to be created on  each node beforehand, e.g:
# for i in worker0 worker2; do ssh root@$i "mkdir /mnt/data; chmod 0777 /data/mnt"; done

---
apiVersion: v1
kind: Namespace
metadata:
  name: consul

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: consul-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-0
  labels:
    type: local
spec:
  storageClassName: consul-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-1
  labels:
    type: local
spec:
  storageClassName: consul-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: consul
  name: data-consul-consul-consul-server-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: consul-storage
  resources:
    requests:
      storage: 200Mi
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: consul
  name: data-consul-consul-consul-server-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: consul-storage
  resources:
    requests:
      storage: 200Mi
